### ISSUE TITLE
Editing an asset

### ISSUE THREAD

**Issue by davidfarmer** [CuratedCourses/server#10]
It does not seem possible to edit the external URL of an asset (such as the link to YouTube).

If possible, it would be helpful to be able to edit that, because we have Canvas links that should
be YouTube links.

Also, the need may also arise when a video has to be modified.

**Comment by kisonecat** [comment]
This is now possible with https://github.com/CuratedCourses/server/commit/cc482bfca66cebc055db283dc70c6783c1d4fd78
