### ISSUE TITLE
Deleting an asset

### ISSUE THREAD

**Issue by davidfarmer** [CuratedCourses/server#5]
I'd like to delete the asset
How to verify & visualize a solution of a linear equation
because the video is unavailable, but I don't see a Delete button.

Well, for that particular asset I would like to change the URL to:
https://www.youtube.com/watch?v=EUANgzCTeu0
but that does not seem to be an option either (Maybe that should be a separate issue.)

**Comment by kisonecat** [comment]
Now it is possible to "retract" an asset.
![retract](https://user-images.githubusercontent.com/148352/43921660-669c1d56-9bea-11e8-801b-ea1ba1e0b981.png)
